kind: pipeline
type: docker
name: twitchandtear
steps:
  - name: build-and-publish-slim
    image: plugins/docker
    settings:
      tags:
        - latest
        - slim
      dockerfile: Dockerfile.slim
      username:
        from_secret: ci_registry_user
      password:
        from_secret: ci_registry_password
      repo:
        from_secret: ci_registry_image
  - name: build-and-publish-full
    image: plugins/docker
    settings:
      tags:
        - full
      dockerfile: Dockerfile.full
      username:
        from_secret: ci_registry_user
      password:
        from_secret: ci_registry_password
      repo:
        from_secret: ci_registry_image
